server:
  port: 8888

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.228.124:3306/sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: sys
    password: ENC(kOszr+P7A1igBzGeAY/bpx0ZLffsMGc/)
    hikari:
      connection-test-query: SELECT 1
