server:
  port: 8888

spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:activiti;DB_CLOSE_DELAY=1000
    username: test
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

